/** Geometry findings are review candidates: intentional clipping and overlap are common UI patterns. */
export function layoutAuditRules(): string {
  return String.raw`
const layoutRule=(id,title,selector,check)=>auditRule('layout',id,title,'warning','heuristic',selector,check);
const layoutControl='button,input:not([type="hidden"]),select,textarea,a[href],[role="button"],[role="textbox"]';
const layoutClip=value=>['hidden','clip'].includes(value);
const layoutSize=r=>Math.round(r.width)+'×'+Math.round(r.height)+'px';
const layoutChildren=(el,c)=>c.all('*').filter(node=>node.parentElement===el&&c.visible(node));
const layoutOverlaps=(el,c)=>{const children=layoutChildren(el,c);for(let i=0;i<Math.min(children.length,100);i++)for(let j=i+1;j<Math.min(children.length,100);j++){const a=c.rect(children[i]),b=c.rect(children[j]);if(Math.min(a.right,b.right)-Math.max(a.left,b.left)>2&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>2)return true}return false};
layoutRule('document-horizontal-overflow','Document exceeds viewport width','@document',(el,c)=>document.documentElement.scrollWidth>document.documentElement.clientWidth+2?'Document width '+document.documentElement.scrollWidth+'px exceeds viewport '+document.documentElement.clientWidth+'px.':null);
layoutRule('horizontal-scroll-locked','Horizontal overflow cannot be scrolled','@document',(el,c)=>{const root=document.documentElement,body=document.body;return root.scrollWidth>root.clientWidth+2&&(layoutClip(c.style(root).overflowX)||body&&layoutClip(c.style(body).overflowX))?'Horizontal content exceeds the viewport while root/body scrolling is hidden or clipped.':null});
layoutRule('vertical-scroll-locked','Vertical overflow cannot be scrolled','@document',(el,c)=>{const root=document.documentElement,body=document.body;return root.scrollHeight>root.clientHeight+2&&(layoutClip(c.style(root).overflowY)||body&&layoutClip(c.style(body).overflowY))?'Vertical content exceeds the viewport while root/body scrolling is hidden or clipped.':null});
layoutRule('clipped-horizontal-content','Container clips horizontal content','*',(el,c)=>c.visible(el)&&!['html','body'].includes(el.localName)&&layoutClip(c.style(el).overflowX)&&el.scrollWidth>el.clientWidth+2?'scrollWidth='+el.scrollWidth+'px; clientWidth='+el.clientWidth+'px; overflow-x='+c.style(el).overflowX+'.':null);
layoutRule('clipped-vertical-content','Container clips vertical content','*',(el,c)=>c.visible(el)&&!['html','body'].includes(el.localName)&&layoutClip(c.style(el).overflowY)&&el.scrollHeight>el.clientHeight+2?'scrollHeight='+el.scrollHeight+'px; clientHeight='+el.clientHeight+'px; overflow-y='+c.style(el).overflowY+'.':null);
layoutRule('zero-width-control','Visible control has no rendered width',layoutControl,(el,c)=>c.visible(el)&&c.rect(el).width<1?'Control box is '+layoutSize(c.rect(el))+'.':null);
layoutRule('zero-height-control','Visible control has no rendered height',layoutControl,(el,c)=>c.visible(el)&&c.rect(el).height<1?'Control box is '+layoutSize(c.rect(el))+'.':null);
layoutRule('offscreen-fixed-element','Fixed element lies outside viewport','*',(el,c)=>{if(!c.visible(el)||c.style(el).position!=='fixed')return null;const r=c.rect(el);return r.width>0&&r.height>0&&(r.right<=0||r.bottom<=0||r.left>=innerWidth||r.top>=innerHeight)?'Fixed box at '+Math.round(r.x)+','+Math.round(r.y)+' is outside '+innerWidth+'×'+innerHeight+'px viewport.':null});
layoutRule('oversized-fixed-element','Fixed element exceeds viewport','*',(el,c)=>c.visible(el)&&c.style(el).position==='fixed'&&(c.rect(el).width>innerWidth+2||c.rect(el).height>innerHeight+2)?'Fixed box '+layoutSize(c.rect(el))+' exceeds '+innerWidth+'×'+innerHeight+'px viewport.':null);
layoutRule('sticky-without-inset','Sticky positioning has no active inset','*',(el,c)=>{const s=c.style(el);return c.visible(el)&&s.position==='sticky'&&[s.top,s.right,s.bottom,s.left].every(v=>v==='auto')?'All four sticky insets are auto; the box will not stick.':null});
layoutRule('sticky-scroll-trap','Sticky element is trapped by a hidden scroll ancestor','*',(el,c)=>{if(!c.visible(el)||c.style(el).position!=='sticky')return null;for(let p=el.parentElement;p&&p!==document.body;p=p.parentElement){const s=c.style(p);if(['hidden','auto','scroll'].includes(s.overflowY))return s.overflowY==='hidden'&&p.scrollHeight>p.clientHeight+2?'Nearest vertical scroll container uses overflow:hidden and has overflowing content.':null}return null});
layoutRule('collapsed-float-container','Container collapses around floated children','*',(el,c)=>c.visible(el)&&c.rect(el).height<1&&layoutChildren(el,c).some(child=>c.style(child).float!=='none'&&c.rect(child).height>1)?'Container height is zero although a floated child has height.':null);
layoutRule('collapsed-positioned-container','Container collapses around positioned children','*',(el,c)=>c.visible(el)&&c.rect(el).height<1&&layoutChildren(el,c).some(child=>c.style(child).position==='absolute'&&c.rect(child).height>1)?'Container height is zero although an absolutely positioned child has height.':null);
layoutRule('overflowing-flex-row','Flex container overflows horizontally','*',(el,c)=>c.visible(el)&&['flex','inline-flex'].includes(c.style(el).display)&&el.scrollWidth>el.clientWidth+2?'Flex content width '+el.scrollWidth+'px exceeds container '+el.clientWidth+'px.':null);
layoutRule('overflowing-grid','Grid content exceeds its width','*',(el,c)=>c.visible(el)&&['grid','inline-grid'].includes(c.style(el).display)&&el.scrollWidth>el.clientWidth+2?'Grid content width '+el.scrollWidth+'px exceeds container '+el.clientWidth+'px.':null);
layoutRule('zero-width-grid-item','Grid item has a zero-width track','*',(el,c)=>c.visible(el)&&el.parentElement&&['grid','inline-grid'].includes(c.style(el.parentElement).display)&&c.rect(el).width<1&&el.scrollWidth>2?'Grid item width is zero but its content needs '+el.scrollWidth+'px.':null);
for(const [id,tag,title] of [['image-wider-than-container','img','Image exceeds container width'],['table-wider-than-container','table','Table exceeds container width'],['pre-wider-than-container','pre','Preformatted block exceeds container width']])layoutRule(id,title,tag,(el,c)=>c.visible(el)&&el.parentElement&&c.rect(el).width>el.parentElement.clientWidth+2?'Rendered width '+Math.round(c.rect(el).width)+'px exceeds parent content area '+el.parentElement.clientWidth+'px.':null);
layoutRule('absolute-outside-container','Absolute box extends beyond its positioning container','*',(el,c)=>{if(!c.visible(el)||c.style(el).position!=='absolute'||!el.offsetParent||el.offsetParent===document.body)return null;const r=c.rect(el),p=c.rect(el.offsetParent);return r.left<p.left-2||r.right>p.right+2||r.top<p.top-2||r.bottom>p.bottom+2?'Absolute box extends outside its offset parent; review overflow and intended anchoring.':null});
layoutRule('negative-inline-start-content','Content crosses the document inline-start edge','*',(el,c)=>{if(!c.visible(el)||c.style(el).position==='fixed')return null;const r=c.rect(el);return r.width>0&&r.height>0&&(c.style(document.documentElement).direction==='rtl'?r.right+scrollX>document.documentElement.scrollWidth+2:r.left+scrollX<-2)?'Box crosses the document inline-start edge and may be unreachable by scrolling.':null});
layoutRule('overlapping-flex-items','Flex siblings overlap','*',(el,c)=>c.visible(el)&&['flex','inline-flex'].includes(c.style(el).display)&&layoutOverlaps(el,c)?'At least two visible direct flex children overlap by more than 2px on both axes; first 100 children inspected.':null);
layoutRule('overlapping-grid-items','Grid siblings overlap','*',(el,c)=>c.visible(el)&&['grid','inline-grid'].includes(c.style(el).display)&&layoutOverlaps(el,c)?'At least two visible direct grid children overlap by more than 2px on both axes; first 100 children inspected.':null);
layoutRule('ineffective-z-index','Static non-layout item declares z-index','*',(el,c)=>{const s=c.style(el);return c.visible(el)&&s.position==='static'&&s.zIndex!=='auto'&&(!el.parentElement||!['flex','inline-flex','grid','inline-grid'].includes(c.style(el.parentElement).display))?'z-index='+s.zIndex+' is set on a static box outside flex/grid item layout.':null});
layoutRule('ineffective-align-self','Block declares align-self outside an alignment layout','*',(el,c)=>{const s=c.style(el);return c.visible(el)&&s.display==='block'&&s.position==='static'&&!['auto','normal'].includes(s.alignSelf)&&el.parentElement&&!['flex','inline-flex','grid','inline-grid'].includes(c.style(el.parentElement).display)?'align-self='+s.alignSelf+' has no flex/grid parent on this static block.':null});
layoutRule('ineffective-order','Order declared outside flex or grid','*',(el,c)=>c.visible(el)&&c.style(el).order!=='0'&&el.parentElement&&!['flex','inline-flex','grid','inline-grid'].includes(c.style(el.parentElement).display)?'order='+c.style(el).order+' has no flex/grid parent.':null);
layoutRule('ineffective-vertical-align','Block declares inline vertical alignment','*',(el,c)=>c.visible(el)&&['block','flex','grid'].includes(c.style(el).display)&&c.style(el).verticalAlign!=='baseline'?'vertical-align='+c.style(el).verticalAlign+' does not align this block box.':null);
layoutRule('hidden-attribute-overridden','Hidden attribute is overridden by rendering styles','[hidden]',(el,c)=>el.getAttribute('hidden')!=='until-found'&&c.style(el).display!=='none'&&c.rect(el).width>0&&c.rect(el).height>0?'The element has hidden but still occupies a visible layout box.':null);
layoutRule('display-contents-control','Control has no principal layout box',layoutControl,(el,c)=>c.style(el).display==='contents'?'display:contents removes the control box; review focus, hit testing and accessibility.':null);
layoutRule('multicolumn-content-clipping','Multicolumn content is clipped horizontally','*',(el,c)=>c.visible(el)&&c.style(el).columnCount!=='auto'&&Number(c.style(el).columnCount)>1&&layoutClip(c.style(el).overflowX)&&el.scrollWidth>el.clientWidth+2?'Additional columns exceed '+el.clientWidth+'px and overflow-x clips them.':null);
`;
}
