/** Markup checks avoid form values; evidence describes relationships, not user input. */
export function markupAuditRules(): string {
  return String.raw`
auditRule('markup','document-language-missing','Document language is missing','warning','observed','@document',el=>!el.lang.trim()?'Expected a nonempty html lang attribute.':null);
// Intl.Locale rejects private-use-only and grandfathered BCP 47 tags accepted by HTML.
const auditLegacyLanguageTags=new Set(['art-lojban','cel-gaulish','en-gb-oed','i-ami','i-bnn','i-default','i-enochian','i-hak','i-klingon','i-lux','i-mingo','i-navajo','i-pwn','i-tao','i-tay','i-tsu','no-bok','no-nyn','sgn-be-fr','sgn-be-nl','sgn-ch-de','zh-guoyu','zh-hakka','zh-min','zh-min-nan','zh-xiang']);
auditRule('markup','document-language-invalid','Document language tag is invalid','warning','heuristic','@document',el=>{const lang=el.lang.trim();if(!lang||/^x(?:-[a-z0-9]{1,8})+$/i.test(lang)||auditLegacyLanguageTags.has(lang.toLowerCase()))return null;try{new Intl.Locale(lang);return null}catch{return 'The browser locale parser rejected html lang; review its BCP 47 syntax.'}});
auditRule('markup','document-title-missing','Document title is missing','warning','observed','@document',()=>!document.title.trim()?'The document has no nonempty title.':null);
auditRule('markup','document-quirks-mode','Document uses quirks mode','warning','observed','@document',()=>document.compatMode!=='CSS1Compat'?'compatMode='+document.compatMode+'; standards layout requires a valid doctype.':null);
auditRule('markup','document-viewport-missing','Mobile viewport declaration is missing','info','heuristic','@document',()=>!document.querySelector('meta[name="viewport" i][content]')?'Responsive rendering may use the browser default layout viewport.':null);
auditRule('markup','duplicate-id','ID is not unique','error','observed','[id]',(el,c)=>el.id&&c.all('[id]').filter(other=>other.id===el.id).length>1?'More than one scanned element has this ID.':null);
auditRule('markup','label-target-missing','Label target does not exist','error','observed','label[for]',el=>!document.getElementById(el.htmlFor)?'The label for attribute has no matching element.':null);
for(const attr of ['labelledby','describedby','controls','owns'])auditRule('markup','aria-'+attr+'-missing','ARIA '+attr+' target does not exist','warning','observed','[aria-'+attr+']',el=>{const refs=(el.getAttribute('aria-'+attr)||'').trim().split(/\s+/).filter(Boolean);const missing=refs.filter(id=>!document.getElementById(id));return missing.length?missing.length+' of '+refs.length+' referenced IDs do not exist.':null});
auditRule('markup','image-alt-missing','Image has no alternative attribute','warning','observed','img',el=>!el.hasAttribute('alt')?'Set meaningful alt text or an explicit empty alt for a decorative image.':null);
auditRule('markup','image-alt-filename','Image alternative resembles a filename','info','heuristic','img[alt]',el=>/\.(png|jpe?g|gif|webp|svg|avif)(\?.*)?$/i.test(el.alt.trim())?'The alternative ends with an image file extension; review its meaning.':null);
auditRule('markup','iframe-name-missing','Frame has no accessible name','warning','observed','iframe',el=>!(el.title.trim()||el.getAttribute('aria-label')?.trim()||el.getAttribute('aria-labelledby')?.trim())?'Add a descriptive frame title or accessible label.':null);
auditRule('markup','button-name-missing','Button has no accessible name','error','observed','button,[role="button"],input[type="button"],input[type="submit"],input[type="reset"]',(el,c)=>{if(el.localName==='input'&&['submit','reset'].includes(el.type)&&!el.hasAttribute('value'))return null;return c.visible(el)&&!accessibleName(el)?'The visible button has an empty computed reader name.':null});
auditRule('markup','link-name-missing','Link has no accessible name','warning','observed','a[href],[role="link"]',(el,c)=>c.visible(el)&&!accessibleName(el)?'The visible link has an empty computed reader name.':null);
auditRule('markup','control-name-missing','Form control has no accessible label','warning','observed','input,select,textarea',(el,c)=>!['hidden','button','submit','reset','image'].includes(el.type)&&c.visible(el)&&!(el.getAttribute('aria-label')?.trim()||el.getAttribute('aria-labelledby')?.trim()||el.labels?.length||el.title.trim())?'No label, aria-label, aria-labelledby or title is associated with this control.':null);
auditRule('markup','main-landmark-missing','Main landmark is missing','info','heuristic','@document',(_el,c)=>!c.all('main,[role="main"]').some(c.visible)?'No visible main landmark was found in the scanned document.':null);
auditRule('markup','main-landmark-duplicate','Multiple main landmarks are visible','warning','heuristic','main,[role="main"]',(el,c)=>c.visible(el)&&c.all('main,[role="main"]').filter(c.visible).length>1?'More than one main landmark is visible; review landmark scope.':null);
auditRule('markup','heading-empty','Heading is empty','warning','observed','h1,h2,h3,h4,h5,h6,[role="heading"]',(el,c)=>c.visible(el)&&!accessibleName(el)?'The visible heading has no accessible text.':null);
auditRule('markup','heading-level-skip','Heading level skips a level','info','heuristic','h1,h2,h3,h4,h5,h6',(el,c)=>{if(!c.visible(el))return null;const headings=c.all('h1,h2,h3,h4,h5,h6').filter(c.visible),i=headings.indexOf(el);return i>0&&Number(el.localName[1])>Number(headings[i-1].localName[1])+1?'Heading follows '+headings[i-1].localName+' with '+el.localName+'.':null});
auditRule('markup','interactive-nesting','Interactive control contains another control','warning','observed','button,a[href],[role="button"]',(el,c)=>c.visible(el)&&!!el.querySelector('button,a[href],input:not([type="hidden"]),select,textarea,[role="button"]')?'Nested controls can receive competing click or keyboard actions.':null);
auditRule('markup','summary-position','Summary is not the first child of details','warning','observed','summary',el=>el.parentElement?.localName!=='details'||el.parentElement.firstElementChild!==el?'A summary should be the first element child of its details.':null);
auditRule('markup','details-summary-missing','Details has no explicit summary','info','heuristic','details',el=>!Array.from(el.children).some(child=>child.localName==='summary')?'The browser supplies a generic disclosure label.':null);
auditRule('markup','table-header-missing','Table has no header cells','info','heuristic','table',(el,c)=>c.visible(el)&&el.getAttribute('role')!=='presentation'&&el.getAttribute('role')!=='none'&&!!el.querySelector('td')&&!el.querySelector('th,[role="columnheader"],[role="rowheader"]')?'If this is a data table, header associations are missing.':null);
auditRule('markup','table-header-reference-missing','Table header reference is invalid','warning','observed','td[headers],th[headers]',el=>{const refs=(el.getAttribute('headers')||'').trim().split(/\s+/).filter(Boolean);return refs.some(id=>{const target=document.getElementById(id);return !target||target.localName!=='th'||target.closest('table')!==el.closest('table')})?'A headers reference does not resolve to a th in the same table.':null});
auditRule('markup','list-child-invalid','List contains an invalid direct child','warning','observed','ul,ol',el=>Array.from(el.children).some(child=>!['li','script','template'].includes(child.localName))?'A ul or ol has a direct child other than li or a script-supporting element.':null);
auditRule('markup','label-target-nonlabelable','Label targets a non-labelable element','warning','observed','label[for]',el=>{const target=document.getElementById(el.htmlFor);return target&&!target.matches('button,meter,output,progress,select,textarea,input:not([type="hidden"])')&&!target.localName.includes('-')?'The target does not support the native label association.':null});
auditRule('markup','aria-hidden-focusable','Focusable control is hidden from accessibility','error','observed','a[href],button,input,select,textarea,[tabindex]',(el,c)=>c.visible(el)&&!el.matches(':disabled')&&!el.closest('[inert]')&&el.tabIndex>=0&&!!el.closest('[aria-hidden="true"]')?'A keyboard-focusable element is inside aria-hidden=true.':null);
auditRule('markup','positive-tabindex','Positive tabindex overrides document order','info','heuristic','[tabindex]',(el,c)=>c.visible(el)&&el.tabIndex>0?'tabindex='+el.tabIndex+' moves this element ahead of the natural focus order.':null);
`;
}
