import {JSDOM} from 'jsdom'
import {describe,expect,it} from 'vitest'
import {previewContextScript,previewInspectorScript} from './previewProxy.js'
import type {PreviewDomAction,PreviewActionResultMessage} from '@voicechat/shared'
function fixture(html:string){const dom=new JSDOM('<!doctype html><body>'+html+'</body>',{url:'http://reader.test/api/preview?url=https%3A%2F%2Fsite.test%2F',runScripts:'dangerously'});const w=dom.window;w.eval(previewContextScript('https://site.test/').replace(/^<script>|<\/script>$/g,''));w.eval(previewInspectorScript().replace(/^<script[^>]*>|<\/script>$/g,''));return{w,close:()=>w.close(),act:(action:PreviewDomAction)=>new Promise<PreviewActionResultMessage>(resolve=>{const requestId='key-'+Math.random();const listener=(e:MessageEvent)=>{if(e.data?.requestId===requestId&&e.data.type==='voicechat.preview.action-result.v1'){w.removeEventListener('message',listener);resolve(e.data)}};w.addEventListener('message',listener);w.dispatchEvent(new w.MessageEvent('message',{source:w as unknown as Window,origin:w.location.origin,data:{type:'voicechat.preview.action.v1',requestId,action}}))})}}
describe('браузерные действия клавиатуры',()=>{
 it('раскладывает chord на key и modifiers',async()=>{const f=fixture('<input id="x">');try{let event:KeyboardEvent|undefined;f.w.document.querySelector('#x')!.addEventListener('keydown',e=>{event=e as KeyboardEvent});expect((await f.act({kind:'press',selector:'#x',key:'Control+Shift+K'})).ok).toBe(true);expect(event).toMatchObject({key:'K',code:'KeyK',ctrlKey:true,shiftKey:true})}finally{f.close()}})
 it('сохраняет code/keyCode для legacy обработчиков',async()=>{const f=fixture('<input id="x">');try{let event:KeyboardEvent|undefined;f.w.document.querySelector('#x')!.addEventListener('keydown',e=>{event=e as KeyboardEvent});await f.act({kind:'press',selector:'#x',key:'Escape'});expect(event).toMatchObject({key:'Escape',code:'Escape',keyCode:27})}finally{f.close()}})
 it('preventDefault отменяет вставку, keyup всё равно приходит',async()=>{const f=fixture('<input id="x" value="old">');try{const el=f.w.document.querySelector('input')!;let up=false;el.addEventListener('keydown',e=>e.preventDefault());el.addEventListener('keyup',()=>{up=true});await f.act({kind:'press',selector:'#x',key:'a'});expect(el.value).toBe('old');expect(up).toBe(true)}finally{f.close()}})
 it('вставка заменяет выделение и шлёт beforeinput/input',async()=>{const f=fixture('<input id="x" value="abcd">');try{const el=f.w.document.querySelector('input')!;el.focus();el.setSelectionRange(1,3);const types:string[]=[];el.addEventListener('beforeinput',e=>types.push((e as InputEvent).inputType));el.addEventListener('input',e=>types.push((e as InputEvent).inputType));await f.act({kind:'press',key:'Z'});expect(el.value).toBe('aZd');expect(types).toEqual(['insertText','insertText'])}finally{f.close()}})
 it('Backspace/Delete не разрывают Unicode пару и удаляют выделение',async()=>{const f=fixture('<input id="x" value="a😀b">');try{const el=f.w.document.querySelector('input')!;el.focus();el.setSelectionRange(3,3);await f.act({kind:'press',key:'Backspace'});expect(el.value).toBe('ab');el.setSelectionRange(0,1);await f.act({kind:'press',key:'Delete'});expect(el.value).toBe('b')}finally{f.close()}})
 it('Control+A, Home и Shift+ArrowRight управляют выделением',async()=>{const f=fixture('<input id="x" value="abc">');try{const el=f.w.document.querySelector('input')!;await f.act({kind:'press',selector:'#x',key:'Control+A'});expect([el.selectionStart,el.selectionEnd]).toEqual([0,3]);await f.act({kind:'press',key:'Home'});await f.act({kind:'press',key:'Shift+ArrowRight'});expect([el.selectionStart,el.selectionEnd]).toEqual([0,1])}finally{f.close()}})
 it('Tab следует tabindex и пропускает hidden/disabled, Shift+Tab идёт назад',async()=>{const f=fixture('<button id="a" tabindex="2">A</button><button id="b" tabindex="1">B</button><button hidden>H</button><button disabled>D</button><input id="c">');try{await f.act({kind:'press',key:'Tab'});expect(f.w.document.activeElement?.id).toBe('b');await f.act({kind:'press',key:'Tab'});expect(f.w.document.activeElement?.id).toBe('a');await f.act({kind:'press',key:'Shift+Tab'});expect(f.w.document.activeElement?.id).toBe('b')}finally{f.close()}})
 it('Enter отправляет валидную форму и учитывает HTML validation',async()=>{const f=fixture('<form><input id="x" required><button>Send</button></form>');try{let count=0;f.w.document.querySelector('form')!.addEventListener('submit',e=>{e.preventDefault();count++});await f.act({kind:'press',selector:'#x',key:'Enter'});expect(count).toBe(0);f.w.document.querySelector('input')!.value='ok';await f.act({kind:'press',selector:'#x',key:'Enter'});expect(count).toBe(1)}finally{f.close()}})
 it('Space переключает checkbox после keyup',async()=>{const f=fixture('<input id="x" type="checkbox">');try{const el=f.w.document.querySelector('input')!;let during=true;el.addEventListener('keyup',()=>{during=el.checked});await f.act({kind:'press',selector:'#x',key:'Space'});expect(during).toBe(false);expect(el.checked).toBe(true)}finally{f.close()}})
 it('select ArrowDown/Home/End пропускает disabled option',async()=>{const f=fixture('<select id="x"><option value="a">A</option><option disabled value="b">B</option><option value="c">C</option></select>');try{const el=f.w.document.querySelector('select')!;await f.act({kind:'press',selector:'#x',key:'ArrowDown'});expect(el.value).toBe('c');await f.act({kind:'press',key:'Home'});expect(el.value).toBe('a');await f.act({kind:'press',key:'End'});expect(el.value).toBe('c')}finally{f.close()}})
})
