import {JSDOM} from 'jsdom'
import {describe,expect,it} from 'vitest'
import {previewContextScript,previewInspectorScript} from './previewProxy.js'
import type {PreviewDomAction,PreviewReadResult,PreviewFindResult,PreviewA11yResult,PreviewActionResultMessage} from '@voicechat/shared'
async function act(html:string,action:PreviewDomAction){const dom=new JSDOM('<!doctype html><body>'+html+'</body>',{url:'http://reader.test/api/preview?url=https%3A%2F%2Fsite.test%2F',runScripts:'dangerously'});const w=dom.window;w.eval(previewContextScript('https://site.test/').replace(/^<script>|<\/script>$/g,''));w.eval(previewInspectorScript().replace(/^<script[^>]*>|<\/script>$/g,''));try{return await new Promise<PreviewActionResultMessage>(resolve=>{w.addEventListener('message',e=>{if(e.data?.type==='voicechat.preview.action-result.v1')resolve(e.data)});w.dispatchEvent(new w.MessageEvent('message',{source:w as unknown as Window,origin:w.location.origin,data:{type:'voicechat.preview.action.v1',requestId:'read-test',action}}))})}finally{w.close()}}
describe('чтение видимой страницы моделью',()=>{
 it('read исключает скрытый текст, скрипты и hidden inputs',async()=>{const r=(await act('<h1>Visible</h1><div hidden>HIDDEN</div><script>/* SOURCE */</script><input type="hidden" value="TOKEN">',{kind:'read'})).result as PreviewReadResult;expect(r.text).toBe('Visible');expect(r.inputs).toEqual([])})
 it('read включает сам корень выбранной области',async()=>{const r=(await act('<h2 id="x">Heading</h2>',{kind:'read',selector:'#x'})).result as PreviewReadResult;expect(r.headings).toEqual([{level:2,text:'Heading'}])})
 it('иконки получают aria-label и alt вместо пустого текста',async()=>{const r=(await act('<button aria-label="Save"><svg></svg></button><a href="/home"><img alt="Home"></a>',{kind:'read'})).result as PreviewReadResult;expect(r.buttons).toEqual(['Save']);expect(r.links[0].text).toBe('Home')})
 it('find исключает скрытые selector matches и находит aria-label',async()=>{const r=(await act('<button hidden>Save</button><button aria-label="Save"></button>',{kind:'find',text:'Save'})).result as PreviewFindResult;expect(r.total).toBe(1);expect(r.elements[0].text).toBe('Save')})
 it('aria-labelledby объединяет все ID и имеет приоритет перед aria-label',async()=>{const r=(await act('<span id="a" hidden>First</span><span id="b">Second</span><button aria-label="Wrong" aria-labelledby="a b">Text</button>',{kind:'a11y'})).result as PreviewA11yResult;expect(r.nodes.find(n=>n.role==='button')?.name).toBe('First Second')})
 it('поле получает все связанные label',async()=>{const r=(await act('<label for="x">First</label><label for="x">Second</label><input id="x">',{kind:'read'})).result as PreviewReadResult;expect(r.inputs[0]).toMatchObject({label:'First Second'})})
 it('a11y исключает aria-hidden и inert вместе с потомками',async()=>{const r=(await act('<div aria-hidden="true"><button>Hidden</button></div><div inert><button>Inert</button></div><button>Visible</button>',{kind:'a11y'})).result as PreviewA11yResult;expect(r.nodes.map(n=>n.name)).toEqual(['Visible'])})
 it('a11y включает роль выбранного корня',async()=>{const r=(await act('<button id="x">Root</button>',{kind:'a11y',selector:'#x'})).result as PreviewA11yResult;expect(r.nodes).toEqual([{role:'button',name:'Root',selector:'#x',level:0}])})
 it('дополнительные native роли и состояния доступны модели',async()=>{const r=(await act('<input type="checkbox" checked disabled><button aria-expanded="false">Menu</button><select multiple><option selected>Choice</option></select><input type="number">',{kind:'a11y'})).result as PreviewA11yResult;expect(r.nodes).toEqual(expect.arrayContaining([expect.objectContaining({role:'checkbox',checked:true,disabled:true}),expect.objectContaining({role:'button',expanded:false}),expect.objectContaining({role:'listbox'}),expect.objectContaining({role:'option',selected:true}),expect.objectContaining({role:'spinbutton'})]))})
 it('маскирует чувствительные поля и сообщает readonly/required',async()=>{const r=(await act('<input name="api_token" value="SECRET"><textarea name="secret">SECRET2</textarea><input id="plain" readonly required value="visible">',{kind:'read'})).result as PreviewReadResult;expect(r.text).not.toContain('SECRET');expect(r.inputs.slice(0,2).map(x=>x.value)).toEqual(['','']);expect(r.inputs[2]).toMatchObject({value:'visible',readOnly:true,required:true})})
})
