// Run against Storybook: node packages/ui/src/components/kanban/kanbanMobile.browser.mjs
import { chromium, expect } from 'playwright/test'
const browser = await chromium.launch({ headless: true })
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true })
const page = await context.newPage()
page.on('pageerror', (error) => console.error(error.message))
const base = process.env.STORYBOOK_URL ?? 'http://127.0.0.1:6018'
const open = async (story) => {
  await page.goto(`${base}/iframe.html?id=kanban-kanbanboard--${story}&viewMode=story`)
  await expect(page.getByTestId('kanban-board')).toBeVisible({ timeout: 30000 })
}
try {
  // @testCase TC1
  await open('mobile-scroll')
  const board = page.getByTestId('kanban-board')
  await expect(page.getByTestId('kanban-column')).toHaveCount(6)
  await expect(page.getByTestId('task-card')).toHaveCount(30)
  await expect(page.getByTestId('board-summary')).toBeHidden()
  await expect(page.getByTestId('priority-overview')).toBeHidden()
  await expect(board).toHaveCSS('scroll-snap-type', 'x mandatory')
  await board.evaluate((element) => { element.scrollLeft = 350 })
  await expect(page.getByText('Колонка 2 из 6')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Колонка 2 из 6')).toBeVisible()
  await page.getByRole('button', { name: 'Предыдущая колонка' }).click()
  const first = page.getByTestId('kanban-column').first()
  const head = first.locator('.jcol-head')
  const before = await head.boundingBox()
  await first.locator('.jcol-content').evaluate((element) => { element.scrollTop = 300 })
  expect((await head.boundingBox()).y).toBe(before.y)
  expect(await first.locator('.jcol-content').evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  await expect(page.getByTestId('board-mobile-create')).toHaveCount(1)
  await expect(page.getByTestId('column-create')).toHaveCount(0)
  await page.getByTestId('board-mobile-create').click()
  await expect(page.getByRole('dialog', { name: 'Создать задачу: Колонка 1' })).toBeVisible()
  await page.keyboard.press('Escape')

  // @testCase TC2
  const card = first.getByTestId('task-card').first()
  await first.locator('.jcol-content').evaluate((element) => { element.scrollTop = 0 })
  await expect(card.locator('.jcard-chips')).toBeHidden()
  await expect(card.locator('.jcard-title')).toBeVisible()
  await expect(card.locator('.jcard-assignee')).toBeVisible()
  await card.getByRole('button', { name: /Действия с/ }).click()
  await page.getByRole('menuitem', { name: 'Все данные карточки' }).click()
  await expect(page.getByRole('dialog')).toContainText('mobile, design, accessibility')
  await page.keyboard.press('Escape')
  const filters = page.getByRole('button', { name: /^Фильтры / })
  await filters.click()
  await page.getByRole('searchbox', { name: 'Поиск на доске', exact: true }).fill('no matching task')
  await page.getByRole('dialog').getByRole('button', { name: 'Сбросить все', exact: true }).focus()
  await page.keyboard.press('Escape')
  await expect(filters).toBeFocused()
  await expect(page.getByText('Под фильтр ничего не попало — сбросить').first()).toBeVisible()
  await filters.click()
  await page.getByRole('dialog').getByRole('button', { name: 'Сбросить все', exact: true }).click()
  await expect(filters).toHaveText('Фильтры (0 активных)')
  await page.getByRole('button', { name: 'Компактная плотность' }).click()
  await page.keyboard.press('Escape')

  // @testCase TC4
  await page.reload()
  await expect(board).toHaveClass(/jboard--density-compact/)
  await first.locator('.jcol-content').evaluate((element) => { element.scrollTop = 0 })

  // @testCase TC3
  await card.focus()
  await page.keyboard.press('Space')
  await page.keyboard.press('ArrowRight')
  await expect(page.getByTestId('kanban-live')).toContainText('колонка Development, позиция')
  await page.keyboard.press('ArrowDown')
  await expect(page.getByTestId('kanban-live')).toContainText('позиция 2 из 4')
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('kanban-live')).toContainText('отменён')
  await page.getByRole('button', { name: 'Предыдущая колонка' }).click()
  const grip = await card.locator('.jcard-grip').boundingBox()
  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: grip.x + 10, y: grip.y + 10 }] })
  await expect(page.locator('.vc-drag-ghost')).toBeVisible()
  expect(await page.locator('.vc-drag-ghost').evaluate((element) => element.style.transform)).toContain('scale(1.02)')
  const startLeft = await board.evaluate((element) => element.scrollLeft)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 373, y: grip.y + 10 }] })
  await expect.poll(() => board.evaluate((element) => element.scrollLeft)).toBeGreaterThan(startLeft)
  await expect(page.locator('[data-drop-target]').first()).toBeAttached()
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
  await expect(page.locator('.vc-drag-ghost')).toHaveCount(0)
  await expect(page.locator('[data-drop-target]')).toHaveCount(0)

  // @testCase TC5
  await page.setViewportSize({ width: 720, height: 844 })
  await expect(board).toHaveCSS('scroll-snap-type', 'x mandatory')
  await page.setViewportSize({ width: 721, height: 844 })
  await expect(page.getByTestId('board-mobile-create')).toHaveCount(0)
  await expect(page.getByTestId('column-create')).toHaveCount(6)
  await page.setViewportSize({ width: 390, height: 844 })
  if (process.env.KANBAN_SCREENSHOT) await page.screenshot({ path: process.env.KANBAN_SCREENSHOT })
  await open('mobile-filters')
  await expect(page.getByRole('dialog', { name: 'Фильтры и меню доски' })).toBeVisible()
  console.log('TC1–TC5 mobile browser checks passed at 390px, 720px and 721px')
} finally {
  await browser.close()
}
