import { JSDOM } from 'jsdom'
import { describe, expect, it } from 'vitest'
import type { PreviewDomAction, PreviewActionResultMessage } from '@voicechat/shared'
import { previewInspectorScript } from './previewProxy.js'
function fixture(html: string) {
  const dom = new JSDOM('<!doctype html><body>'+html+'</body>',{url:'https://reader.test/api/preview?url=https%3A%2F%2Fsite.test%2F',runScripts:'dangerously'})
  const w=dom.window;w.eval(previewInspectorScript().replace(/^<script[^>]*>/,'').replace(/<\/script>$/,''));let id=0
  return {w,close:()=>w.close(),act:(action:PreviewDomAction)=>new Promise<PreviewActionResultMessage>(resolve=>{const requestId=String(++id);const receive=(event:MessageEvent)=>{if(event.data?.type==='voicechat.preview.action-result.v1'&&event.data.requestId===requestId){w.removeEventListener('message',receive);resolve(event.data)}};w.addEventListener('message',receive);w.dispatchEvent(new w.MessageEvent('message',{origin:w.location.origin,source:w as unknown as Window,data:{type:'voicechat.preview.action.v1',requestId,action}}))})}
}
describe('точность интерактивных действий Reader',()=>{
  it('поиск текста игнорирует скрытые узлы и содержимое script/style',async()=>{const f=fixture('<button hidden>Продолжить</button><button id="live">Продолжить</button><script>/* Продолжить */</script>');try{let clicked=false;f.w.document.querySelector('#live')!.addEventListener('click',()=>{clicked=true});expect((await f.act({kind:'click',text:'Продолжить'})).ok).toBe(true);expect(clicked).toBe(true)}finally{f.close()}})
  it('не выбирает первый из нескольких одинаковых селекторов',async()=>{const f=fixture('<button>Один</button><button>Два</button>');try{let clicks=0;f.w.document.addEventListener('click',()=>clicks++);expect(await f.act({kind:'click',selector:'button'})).toMatchObject({ok:false,error:expect.stringContaining('неоднозначен')});expect(clicks).toBe(0)}finally{f.close()}})
  it.each(['<button id="x" disabled>Нет</button>','<fieldset disabled><button id="x">Нет</button></fieldset>','<div aria-disabled="true"><button id="x">Нет</button></div>','<div inert><button id="x">Нет</button></div>'])('не сообщает успех отключённому элементу %s',async html=>{const f=fixture(html);try{expect(await f.act({kind:'click',selector:'#x'})).toMatchObject({ok:false,error:expect.stringContaining('отключён')})}finally{f.close()}})
  it('клик включает pointer/mouse/focus в браузерном порядке',async()=>{const f=fixture('<button id="x">Да</button>');try{const events:string[]=[];const button=f.w.document.querySelector('#x')!;for(const event of ['pointerdown','mousedown','focus','pointerup','mouseup','click'])button.addEventListener(event,()=>events.push(event));expect((await f.act({kind:'click',selector:'#x'})).ok).toBe(true);expect(events).toEqual(['pointerdown','mousedown','focus','pointerup','mouseup','click']);expect(f.w.document.activeElement).toBe(button)}finally{f.close()}})
  it('type и set не меняют readonly поле',async()=>{const f=fixture('<input id="x" readonly value="old">');try{for(const action of [{kind:'type',selector:'#x',text:'new'},{kind:'set',selector:'#x',value:'new'}] as PreviewDomAction[])expect((await f.act(action)).ok).toBe(false);expect((f.w.document.querySelector('#x') as HTMLInputElement).value).toBe('old')}finally{f.close()}})
  it.each(['checkbox','radio','file','button'])('type не меняет значение контрола %s',async type=>{const f=fixture('<input id="x" type="'+type+'">');try{expect(await f.act({kind:'type',selector:'#x',text:'wrong'})).toMatchObject({ok:false,error:expect.stringContaining('set, upload или click')})}finally{f.close()}})
  it('beforeinput получает данные и может отменить изменение',async()=>{const f=fixture('<input id="x" value="old">');try{let data='';f.w.document.querySelector('#x')!.addEventListener('beforeinput',event=>{data=(event as InputEvent).data!;event.preventDefault()});expect(await f.act({kind:'type',selector:'#x',text:'new'})).toMatchObject({ok:false,error:expect.stringContaining('отклонила')});expect(data).toBe('new');expect((f.w.document.querySelector('#x') as HTMLInputElement).value).toBe('old')}finally{f.close()}})
  it('maxlength и неверное число проверяются до мутации',async()=>{const f=fixture('<input id="short" maxlength="2" value="ok"><input id="number" type="number" value="42">');try{expect((await f.act({kind:'type',selector:'#short',text:'long'})).ok).toBe(false);expect((await f.act({kind:'type',selector:'#number',text:'not-number'})).ok).toBe(false);expect((f.w.document.querySelector('#short') as HTMLInputElement).value).toBe('ok');expect((f.w.document.querySelector('#number') as HTMLInputElement).value).toBe('42')}finally{f.close()}})
  it('select не выбирает отсутствующую/отключённую опцию',async()=>{const f=fixture('<select id="x"><option value="old">Old</option><option disabled value="disabled">No</option><optgroup disabled><option value="group">No group</option></optgroup></select>');try{for(const value of ['missing','disabled','group'])expect((await f.act({kind:'set',selector:'#x',value})).ok).toBe(false);expect((f.w.document.querySelector('#x') as HTMLSelectElement).value).toBe('old')}finally{f.close()}})
  it('radio=false и отменённый checkbox не дают ложного успеха',async()=>{const f=fixture('<input id="r" type="radio" checked><input id="c" type="checkbox">');try{f.w.document.querySelector('#c')!.addEventListener('click',event=>event.preventDefault());expect((await f.act({kind:'set',selector:'#r',checked:false})).ok).toBe(false);expect((await f.act({kind:'set',selector:'#c',checked:true})).ok).toBe(false);expect((f.w.document.querySelector('#r') as HTMLInputElement).checked).toBe(true);expect((f.w.document.querySelector('#c') as HTMLInputElement).checked).toBe(false)}finally{f.close()}})
})
