import { describe, expect, it } from 'vitest'
import { PreviewCookieStore, responseSetCookies } from './previewCookies'
const url = (path = '/', host = 'shop.example.com', protocol = 'https:') => new URL(protocol + '//' + host + path)
describe('cookie-контейнер Reader', () => {
  it('не отправляет host-only cookie поддоменам', () => { const store = new PreviewCookieStore(); store.store('a', url(), 'sid=one'); expect(store.header('a', url())).toBe('sid=one'); expect(store.header('a', url('/', 'child.shop.example.com'))).toBeUndefined() })
  it('явный Domain включает поддомены и не включает похожий suffix', () => { const store = new PreviewCookieStore(); store.store('a', url(), 'sid=one; Domain=example.com'); expect(store.header('a', url('/', 'other.example.com'))).toBe('sid=one'); expect(store.header('a', url('/', 'notexample.com'))).toBeUndefined() })
  it('Path соблюдает границу сегмента', () => { const store = new PreviewCookieStore(); store.store('a', url(), 'sid=one; Path=/app'); expect(store.header('a', url('/app'))).toBe('sid=one'); expect(store.header('a', url('/app/page'))).toBe('sid=one'); expect(store.header('a', url('/apple'))).toBeUndefined() })
  it('default-path включает родительский путь без завершающего slash', () => { const store = new PreviewCookieStore(); store.store('a', url('/app/login'), 'sid=one'); expect(store.header('a', url('/app'))).toBe('sid=one'); expect(store.header('a', url('/app/next'))).toBe('sid=one'); expect(store.header('a', url('/'))).toBeUndefined() })
  it('Max-Age сильнее Expires при любом порядке атрибутов', () => { for (const attributes of ['Max-Age=3600; Expires=Thu, 01 Jan 1970 00:00:00 GMT','Expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=3600']) { const store = new PreviewCookieStore(); store.store('a',url(), 'sid=one; '+attributes); expect(store.header('a',url())).toBe('sid=one') } })
  it('не принимает Domain публичного суффикса и общего домена машин', () => { const store = new PreviewCookieStore(); store.store('a', url(), ['a=1; Domain=com','b=1; Domain=co.uk']); store.store('a', url('/', 'one.machine.internal'), 'shared=1; Domain=machine.internal'); expect(store.header('a', url('/', 'other.com'))).toBeUndefined(); expect(store.header('a', url('/', 'two.machine.internal'))).toBeUndefined() })
  it('Secure не устанавливается по HTTP и не отправляется в него', () => { const store = new PreviewCookieStore(); store.store('a', url('/', 'shop.example.com','http:'), 'insecure=1; Secure'); expect(store.header('a', url())).toBeUndefined(); store.store('a', url(), 'secure=1; Secure'); expect(store.header('a', url())).toBe('secure=1'); expect(store.header('a', url('/', 'shop.example.com','http:'))).toBeUndefined() })
  it('соблюдает обязательные атрибуты __Host- и __Secure-', () => { const store = new PreviewCookieStore(); store.store('a', url(), ['__Host-bad=1; Secure; Domain=example.com; Path=/','__Secure-bad=1','__Host-good=1; Secure; Path=/']); expect(store.header('a', url())).toBe('__Host-good=1') })
  it('Expires epoch и Max-Age=0 действительно удаляют cookie', () => { const store = new PreviewCookieStore(); for (const deletion of ['Expires=Thu, 01 Jan 1970 00:00:00 GMT','Max-Age=0; Expires=Wed, 01 Jan 2099 00:00:00 GMT']) { store.store('a', url(),'sid=one; Path=/'); store.store('a',url(),'sid=gone; Path=/; '+deletion); expect(store.header('a',url())).toBeUndefined() } })
  it('не делит cookie между пользователями и экземплярами сервера', () => { const first = new PreviewCookieStore(), second = new PreviewCookieStore(); first.store('a', url(),'sid=one'); expect(first.header('b',url())).toBeUndefined(); expect(second.header('a',url())).toBeUndefined() })
  it('сохраняет все варианты регистра Set-Cookie', () => expect(responseSetCookies({ 'Set-Cookie': ['a=1','b=2'], 'set-cookie': 'c=3', other: 'x' })).toEqual(['a=1','b=2','c=3']))
  it('сброс сайта не удаляет другой сайт или пользователя', () => { const store = new PreviewCookieStore(); store.store('a',url(),'sid=one'); store.store('a',url('/','other.test'),'other=one'); store.store('b',url(),'sid=two'); expect(store.clear('a','SHOP.EXAMPLE.COM')).toBe(1); expect(store.header('a',url('/','other.test'))).toBe('other=one'); expect(store.header('b',url())).toBe('sid=two') })
  it('сортирует cookie по длине пути, а равные — по созданию', () => { const store = new PreviewCookieStore(); store.store('a',url(),['a=one; Path=/','b=two; Path=/','a=three; Path=/app']); expect(store.header('a',url('/app'))).toBe('a=three; a=one; b=two') })
  it('повреждённый или слишком большой заголовок не ломает соседние cookie', () => { const store = new PreviewCookieStore(); store.store('a',url(),['=wrong','big='+ 'x'.repeat(4096), 'good=1']); expect(store.header('a',url())).toBe('good=1') })
})
