import {describe,expect,it} from 'vitest'
import {join} from 'node:path'
import {setupRestHarness} from './restHarness.js'
import {VoiceChatDb} from '../db/database.js'
import {createLocalPlaywrightReaderCore} from '../playwrightReaderBridge/localCore.js'
const h=setupRestHarness()
async function create(kind='web-recorder'){return(await h.inj({method:'POST',url:'/api/conversations',payload:{title:'Reader engine',assistantKind:kind}})).json()}
describe('выбор полного браузера в разговоре Web Reader',()=>{
 it('по умолчанию использует proxy и сохраняет Chromium вместе с URL',async()=>{const c=await create();expect(c.previewEngine).toBe('proxy');const response=await h.inj({method:'POST',url:`/api/conversations/${c.id}/preview-url`,payload:{previewUrl:'https://mail.google.com/',previewEngine:'chromium'}});expect(response.statusCode).toBe(200);expect(response.json()).toMatchObject({id:c.id,assistantKind:'web-recorder',previewEngine:'chromium',previewUrl:'https://mail.google.com/'})})
 it('обычное сохранение адреса не сбрасывает выбранный движок',async()=>{const c=await create();await h.db.chat.setConversationPreviewUrl(h.U,c.id,'https://example.com/','chromium');const response=await h.inj({method:'POST',url:`/api/conversations/${c.id}/preview-url`,payload:{previewUrl:'https://www.instagram.com/'}});expect(response.json()).toMatchObject({previewEngine:'chromium',previewUrl:'https://www.instagram.com/'})})
 it('отвергает неверный движок и неверный тип URL без записи',async()=>{const c=await create();for(const payload of [{previewEngine:'unknown',previewUrl:'https://x.test/'},{previewEngine:'chromium',previewUrl:42}])expect((await h.inj({method:'POST',url:`/api/conversations/${c.id}/preview-url`,payload})).statusCode).toBe(400);expect((await h.db.chat.getConversation(h.U,c.id))?.previewEngine).toBe('proxy')})
 it('не меняет чужой разговор и не переключает Make',async()=>{const other=await h.db.chat.createConversation('other','Private');expect((await h.inj({method:'POST',url:`/api/conversations/${other.id}/preview-url`,payload:{previewEngine:'chromium'}})).statusCode).toBe(404);const make=await create('make');expect((await h.inj({method:'POST',url:`/api/conversations/${make.id}/preview-url`,payload:{previewEngine:'chromium'}})).statusCode).toBe(403)})
 it('ядро направляет модель в выбранный Chromium и возвращает relay после переключения',async()=>{const c=await create();const core=createLocalPlaywrightReaderCore({db:h.db,issuePreviewRunKey:()=> 'key',logBrowserShot:async()=>{}});expect(await core.modelTarget(h.U,c.id)).toBeNull();await h.db.chat.setConversationPreviewUrl(h.U,c.id,'https://example.com/','chromium');expect(await core.conversation(h.U,c.id)).toMatchObject({previewEngine:'chromium'});expect(await core.modelTarget(h.U,c.id)).toEqual({sessionId:c.id,conversationKey:c.id,profileMode:'persistent'});expect(await core.modelTarget('other',c.id)).toBeNull();await h.db.chat.setConversationPreviewUrl(h.U,c.id,'https://example.com/','proxy');expect(await core.modelTarget(h.U,c.id)).toBeNull()})
 it('выбор движка переживает открытие базы новым процессом',async()=>{const path=join(h.dataDir,'engine-persistent.db');let db=new VoiceChatDb(path);await db.ready;let id='';try{const c=await db.chat.createConversation(h.U,'Persistent');id=c.id;await db.chat.setConversationPreviewUrl(h.U,id,'https://example.com/','chromium')}finally{await db.close()}db=new VoiceChatDb(path);await db.ready;try{expect((await db.chat.getConversation(h.U,id))?.previewEngine).toBe('chromium')}finally{await db.close()}})
})
