import fastify, { type FastifyInstance } from 'fastify'
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { chromium, type Browser, type Page } from 'playwright'
import type { PreviewDomAction, PreviewActionResultMessage } from '@voicechat/shared'
import { registerPreviewProxy } from '../apps/web-reader/src/routes/previewProxy.js'
let app: FastifyInstance, browser: Browser, page: Page, base: string, source = ''
const inner = () => page.frameLocator('iframe')
async function open(html: string) { source='<!doctype html><body>'+html+'</body>';await page.goto(base+'/host');await inner().locator('#voicechat-preview-inspector').waitFor({state:'attached'}) }
async function act(action: PreviewDomAction): Promise<PreviewActionResultMessage> {
  return page.evaluate(action=>new Promise<PreviewActionResultMessage>(resolve=>{const frame=document.querySelector('iframe')!.contentWindow!,requestId=crypto.randomUUID();const receive=(event:MessageEvent)=>{if(event.source!==frame||event.origin!==location.origin||event.data?.requestId!==requestId||event.data.type!=='voicechat.preview.action-result.v1')return;removeEventListener('message',receive);resolve(event.data)};addEventListener('message',receive);frame.postMessage({type:'voicechat.preview.action.v1',requestId,action},location.origin)}),action)
}
describe('Reader: действия клавиатуры в Chromium',()=>{
  beforeAll(async()=>{app=fastify();app.addHook('onRequest',async req=>{;(req as unknown as{user:{name:string;role:string}}).user={name:'interactions-e2e',role:'user'}});app.get('/host',async(_req,reply)=>reply.type('text/html').send('<!doctype html><iframe style="width:900px;height:650px" src="/api/preview?url=http%3A%2F%2Finteractions.machine.internal%3A5173%2F"></iframe>'));registerPreviewProxy(app,{machines:{canUse:async()=>true,bridge:{isOnline:()=>true,http:async()=>({status:200,headers:{'content-type':'text/html; charset=utf-8'},bodyBase64:Buffer.from(source).toString('base64')})}}});base=await app.listen({host:'127.0.0.1',port:0});browser=await chromium.launch()})
  beforeEach(async()=>{page=await browser.newPage();page.setDefaultTimeout(5000)});afterEach(async()=>{await page?.close()});afterAll(async()=>{await browser?.close();await app?.close()})
 it('раскладывает Control+Shift+K на key и modifiers',async()=>{await open('<input id="x"><script>document.querySelector("input").addEventListener("keydown",e=>document.body.dataset.key=JSON.stringify({key:e.key,code:e.code,ctrl:e.ctrlKey,shift:e.shiftKey}))</script>');expect((await act({kind:'press',selector:'#x',key:'Control+Shift+K'})).ok).toBe(true);expect(JSON.parse((await inner().locator('body').getAttribute('data-key'))!)).toEqual({key:'K',code:'KeyK',ctrl:true,shift:true})})
 it('Escape несёт code и legacy keyCode',async()=>{await open('<input id="x"><script>document.querySelector("input").addEventListener("keydown",e=>document.body.dataset.key=JSON.stringify({code:e.code,keyCode:e.keyCode}))</script>');await act({kind:'press',selector:'#x',key:'Escape'});expect(JSON.parse((await inner().locator('body').getAttribute('data-key'))!)).toEqual({code:'Escape',keyCode:27})})
 it('preventDefault отменяет изменение поля, сохраняя keyup',async()=>{await open('<input id="x" value="old"><script>const x=document.querySelector("input");x.addEventListener("keydown",e=>e.preventDefault());x.addEventListener("keyup",()=>document.body.dataset.up="yes")</script>');await act({kind:'press',selector:'#x',key:'a'});expect(await inner().locator('#x').inputValue()).toBe('old');expect(await inner().locator('body').getAttribute('data-up')).toBe('yes')})
 it('печатный символ заменяет выделение через beforeinput/input',async()=>{await open('<input id="x" value="abcd"><script>for(const t of ["beforeinput","input"])document.querySelector("input").addEventListener(t,e=>document.body.dataset[t]=e.inputType)</script>');await inner().locator('#x').evaluate((el:HTMLInputElement)=>{el.focus();el.setSelectionRange(1,3)});await act({kind:'press',key:'Z'});expect(await inner().locator('#x').inputValue()).toBe('aZd');expect(await inner().locator('body').getAttribute('data-beforeinput')).toBe('insertText');expect(await inner().locator('body').getAttribute('data-input')).toBe('insertText')})
 it('Backspace/Delete сохраняют целостность Unicode и удаляют выделение',async()=>{await open('<input id="x" value="a😀b">');await inner().locator('#x').evaluate((el:HTMLInputElement)=>{el.focus();el.setSelectionRange(3,3)});await act({kind:'press',key:'Backspace'});expect(await inner().locator('#x').inputValue()).toBe('ab');await inner().locator('#x').evaluate((el:HTMLInputElement)=>el.setSelectionRange(0,1));await act({kind:'press',key:'Delete'});expect(await inner().locator('#x').inputValue()).toBe('b')})
 it('Backspace на границе contenteditable не удаляет соседний документ',async()=>{await open('<p id="outside">Снаружи</p><div id="edit" contenteditable="true">Внутри</div>');await inner().locator('#edit').evaluate(el=>{(el as HTMLElement).focus();const range=document.createRange();range.selectNodeContents(el);range.collapse(true);getSelection()!.removeAllRanges();getSelection()!.addRange(range)});expect((await act({kind:'press',key:'Backspace'})).ok).toBe(true);expect(await inner().locator('#outside').textContent()).toBe('Снаружи');expect(await inner().locator('#edit').textContent()).toBe('Внутри')})
 it('Control+A, Home и Shift+ArrowRight меняют выделение',async()=>{await open('<input id="x" value="abc">');await act({kind:'press',selector:'#x',key:'Control+A'});expect(await inner().locator('#x').evaluate((el:HTMLInputElement)=>[el.selectionStart,el.selectionEnd])).toEqual([0,3]);await act({kind:'press',key:'Home'});await act({kind:'press',key:'Shift+ArrowRight'});expect(await inner().locator('#x').evaluate((el:HTMLInputElement)=>[el.selectionStart,el.selectionEnd])).toEqual([0,1])})
 it('Tab следует tabindex и пропускает hidden/disabled, Shift+Tab возвращается',async()=>{await open('<button id="a" tabindex="2">A</button><button id="b" tabindex="1">B</button><button hidden>Hidden</button><button disabled>Disabled</button><input id="c">');await act({kind:'press',key:'Tab'});expect(await inner().locator('body').evaluate(()=>document.activeElement?.id)).toBe('b');await act({kind:'press',key:'Tab'});expect(await inner().locator('body').evaluate(()=>document.activeElement?.id)).toBe('a');await act({kind:'press',key:'Shift+Tab'});expect(await inner().locator('body').evaluate(()=>document.activeElement?.id)).toBe('b')})
 it('Enter проверяет required и отправляет форму через submitter',async()=>{await open('<form><input id="x" required><button id="send">Send</button></form><script>document.querySelector("form").addEventListener("submit",e=>{e.preventDefault();document.body.dataset.submitted=e.submitter?.id})</script>');await act({kind:'press',selector:'#x',key:'Enter'});expect(await inner().locator('body').getAttribute('data-submitted')).toBeNull();await inner().locator('#x').fill('ok');await act({kind:'press',selector:'#x',key:'Enter'});expect(await inner().locator('body').getAttribute('data-submitted')).toBe('send')})
 it('Space переключает checkbox после keyup',async()=>{await open('<input id="x" type="checkbox"><script>document.querySelector("input").addEventListener("keyup",e=>document.body.dataset.checked=String(e.target.checked))</script>');await act({kind:'press',selector:'#x',key:'Space'});expect(await inner().locator('body').getAttribute('data-checked')).toBe('false');expect(await inner().locator('#x').isChecked()).toBe(true)})
 it('стрелки select пропускают disabled и отправляют change',async()=>{await open('<select id="x"><option value="a">A</option><option disabled value="b">B</option><option value="c">C</option></select><script>document.querySelector("select").addEventListener("change",e=>document.body.dataset.selected=e.target.value)</script>');await act({kind:'press',selector:'#x',key:'ArrowDown'});expect(await inner().locator('#x').inputValue()).toBe('c');expect(await inner().locator('body').getAttribute('data-selected')).toBe('c');await act({kind:'press',key:'Home'});expect(await inner().locator('#x').inputValue()).toBe('a');await act({kind:'press',key:'End'});expect(await inner().locator('#x').inputValue()).toBe('c')})
})
