import fastify, { type FastifyInstance } from 'fastify'
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { chromium, type Browser, type Page } from 'playwright'
import type { PreviewDomAction, PreviewActionResultMessage, PreviewReadResult, PreviewFindResult, PreviewA11yResult } from '@voicechat/shared'
import { registerPreviewProxy } from '../apps/web-reader/src/routes/previewProxy.js'
let app: FastifyInstance, browser: Browser, page: Page, base: string, source = ''
const inner = () => page.frameLocator('iframe')
async function open(html: string) { source='<!doctype html><body>'+html+'</body>';await page.goto(base+'/host');await inner().locator('#voicechat-preview-inspector').waitFor({state:'attached'}) }
async function sendAction(action: PreviewDomAction): Promise<PreviewActionResultMessage> {
  return page.evaluate(action=>new Promise<PreviewActionResultMessage>(resolve=>{const frame=document.querySelector('iframe')!.contentWindow!,requestId=crypto.randomUUID();const receive=(event:MessageEvent)=>{if(event.source!==frame||event.origin!==location.origin||event.data?.requestId!==requestId||event.data.type!=='voicechat.preview.action-result.v1')return;removeEventListener('message',receive);resolve(event.data)};addEventListener('message',receive);frame.postMessage({type:'voicechat.preview.action.v1',requestId,action},location.origin)}),action)
}
async function act(html:string, action:PreviewDomAction){await open(html);return sendAction(action)}
describe('Reader: семантическое чтение в Chromium',()=>{
  beforeAll(async()=>{app=fastify();app.addHook('onRequest',async req=>{;(req as unknown as{user:{name:string;role:string}}).user={name:'interactions-e2e',role:'user'}});app.get('/host',async(_req,reply)=>reply.type('text/html').send('<!doctype html><iframe style="width:900px;height:650px" src="/api/preview?url=http%3A%2F%2Finteractions.machine.internal%3A5173%2F"></iframe>'));registerPreviewProxy(app,{machines:{canUse:async()=>true,bridge:{isOnline:()=>true,http:async()=>({status:200,headers:{'content-type':'text/html; charset=utf-8'},bodyBase64:Buffer.from(source).toString('base64')})}}});base=await app.listen({host:'127.0.0.1',port:0});browser=await chromium.launch()})
  beforeEach(async()=>{page=await browser.newPage();page.setDefaultTimeout(5000)});afterEach(async()=>{await page?.close()});afterAll(async()=>{await browser?.close();await app?.close()})
 it('read исключает скрытый текст, скрипты и hidden inputs',async()=>{const r=(await act('<h1>Visible</h1><div hidden>HIDDEN</div><script>/* SOURCE */</script><input type="hidden" value="TOKEN">',{kind:'read'})).result as PreviewReadResult;expect(r.text).toBe('Visible');expect(r.inputs).toEqual([])})
 it('read включает сам корень выбранной области',async()=>{const r=(await act('<h2 id="x">Heading</h2>',{kind:'read',selector:'#x'})).result as PreviewReadResult;expect(r.headings).toEqual([{level:2,text:'Heading'}])})
 it('иконки получают aria-label и alt вместо пустого текста',async()=>{const r=(await act('<button aria-label="Save"><svg></svg></button><a href="/home"><img alt="Home"></a>',{kind:'read'})).result as PreviewReadResult;expect(r.buttons).toEqual(['Save']);expect(r.links[0].text).toBe('Home')})
 it('find исключает скрытые selector matches и находит aria-label',async()=>{const r=(await act('<button hidden>Save</button><button aria-label="Save"></button>',{kind:'find',text:'Save'})).result as PreviewFindResult;expect(r.total).toBe(1);expect(r.elements[0].text).toBe('Save')})
 it('aria-labelledby объединяет все ID и имеет приоритет перед aria-label',async()=>{const r=(await act('<span id="a" hidden>First</span><span id="b">Second</span><button aria-label="Wrong" aria-labelledby="a b">Text</button>',{kind:'a11y'})).result as PreviewA11yResult;expect(r.nodes.find(n=>n.role==='button')?.name).toBe('First Second')})
 it('поле получает все связанные label',async()=>{const r=(await act('<label for="x">First</label><label for="x">Second</label><input id="x">',{kind:'read'})).result as PreviewReadResult;expect(r.inputs[0]).toMatchObject({label:'First Second'})})
 it('a11y исключает aria-hidden и inert вместе с потомками',async()=>{const r=(await act('<div aria-hidden="true"><button>Hidden</button></div><div inert><button>Inert</button></div><button>Visible</button>',{kind:'a11y'})).result as PreviewA11yResult;expect(r.nodes.map(n=>n.name)).toEqual(['Visible'])})
 it('a11y включает роль выбранного корня',async()=>{const r=(await act('<button id="x">Root</button>',{kind:'a11y',selector:'#x'})).result as PreviewA11yResult;expect(r.nodes).toEqual([{role:'button',name:'Root',selector:'#x',level:0}])})
 it('дополнительные native роли и состояния доступны модели',async()=>{const r=(await act('<input type="checkbox" checked disabled><button aria-expanded="false">Menu</button><select multiple><option selected>Choice</option></select><input type="number">',{kind:'a11y'})).result as PreviewA11yResult;expect(r.nodes).toEqual(expect.arrayContaining([expect.objectContaining({role:'checkbox',checked:true,disabled:true}),expect.objectContaining({role:'button',expanded:false}),expect.objectContaining({role:'listbox'}),expect.objectContaining({role:'option',selected:true}),expect.objectContaining({role:'spinbutton'})]))})
 it('маскирует чувствительные поля и сообщает readonly/required',async()=>{const r=(await act('<input name="api_token" value="SECRET"><textarea name="secret">SECRET2</textarea><input id="plain" readonly required value="visible">',{kind:'read'})).result as PreviewReadResult;expect(r.text).not.toContain('SECRET');expect(r.inputs.slice(0,2).map(x=>x.value)).toEqual(['','']);expect(r.inputs[2]).toMatchObject({value:'visible',readOnly:true,required:true})})
})
