import fastify, { type FastifyInstance } from 'fastify'
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest'
import { chromium, type Browser, type Page } from 'playwright'
import type { PreviewDomAction, PreviewActionResultMessage } from '@voicechat/shared'
import { registerPreviewProxy } from '../apps/web-reader/src/routes/previewProxy.js'
let app: FastifyInstance, browser: Browser, page: Page, base: string, source = ''
const inner = () => page.frameLocator('iframe')
async function open(html: string) { source='<!doctype html><body>'+html+'</body>';await page.goto(base+'/host');await inner().locator('#voicechat-preview-inspector').waitFor({state:'attached'}) }
async function act(action: PreviewDomAction): Promise<PreviewActionResultMessage> {
  return page.evaluate(action=>new Promise<PreviewActionResultMessage>(resolve=>{const frame=document.querySelector('iframe')!.contentWindow!,requestId=crypto.randomUUID();const receive=(event:MessageEvent)=>{if(event.source!==frame||event.origin!==location.origin||event.data?.requestId!==requestId||event.data.type!=='voicechat.preview.action-result.v1')return;removeEventListener('message',receive);resolve(event.data)};addEventListener('message',receive);frame.postMessage({type:'voicechat.preview.action.v1',requestId,action},location.origin)}),action)
}
describe('Reader: действия модели с интерактивными элементами в Chromium',()=>{
  beforeAll(async()=>{app=fastify();app.addHook('onRequest',async req=>{;(req as unknown as{user:{name:string;role:string}}).user={name:'interactions-e2e',role:'user'}});app.get('/host',async(_req,reply)=>reply.type('text/html').send('<!doctype html><iframe style="width:900px;height:650px" src="/api/preview?url=http%3A%2F%2Finteractions.machine.internal%3A5173%2F"></iframe>'));registerPreviewProxy(app,{machines:{canUse:async()=>true,bridge:{isOnline:()=>true,http:async()=>({status:200,headers:{'content-type':'text/html; charset=utf-8'},bodyBase64:Buffer.from(source).toString('base64')})}}});base=await app.listen({host:'127.0.0.1',port:0});browser=await chromium.launch()})
  beforeEach(async()=>{page=await browser.newPage();page.setDefaultTimeout(5000)});afterEach(async()=>{await page?.close()});afterAll(async()=>{await browser?.close();await app?.close()})
  it('кликает видимый текст, игнорируя скрытый дубликат и script',async()=>{await open('<button style="display:none">Продолжить</button><button id="live" onclick="this.dataset.clicked=\'yes\'">Продолжить</button><script>/* Продолжить */</script>');expect((await act({kind:'click',text:'Продолжить'})).ok).toBe(true);expect(await inner().locator('#live').getAttribute('data-clicked')).toBe('yes')})
  it('отказывается выбирать случайную кнопку неоднозначного селектора',async()=>{await open('<button onclick="this.remove()">Первый</button><button onclick="this.remove()">Второй</button>');expect(await act({kind:'click',selector:'button'})).toMatchObject({ok:false,error:expect.stringContaining('неоднозначен')});expect(await inner().locator('button').count()).toBe(2)})
  it('не выдаёт успех disabled, fieldset и aria-disabled',async()=>{await open('<button id="a" disabled>Нет</button><fieldset disabled><button id="b">Нет</button></fieldset><div aria-disabled="true"><button id="c">Нет</button></div>');for(const selector of ['#a','#b','#c'])expect((await act({kind:'click',selector})).ok).toBe(false)})
  it('выполняет полный pointer/mouse-путь с фокусом',async()=>{await open('<button id="x">Да</button><script>window.events=[];for(const type of ["pointerdown","mousedown","focus","pointerup","mouseup","click"])document.querySelector("#x").addEventListener(type,()=>events.push(type))</script>');expect((await act({kind:'click',selector:'#x'})).ok).toBe(true);expect(await inner().locator('body').evaluate(()=>(window as unknown as{events:string[]}).events)).toEqual(['pointerdown','mousedown','focus','pointerup','mouseup','click']);expect(await inner().locator('#x').evaluate(el=>document.activeElement===el)).toBe(true)})
  it('readonly значение остаётся неизменным',async()=>{await open('<input id="x" readonly value="original">');expect((await act({kind:'type',selector:'#x',text:'changed'})).ok).toBe(false);expect(await inner().locator('#x').inputValue()).toBe('original')})
  it('type не подменяет value checkbox вместо переключения',async()=>{await open('<input id="x" type="checkbox" value="original">');expect((await act({kind:'type',selector:'#x',text:'changed'})).ok).toBe(false);expect(await inner().locator('#x').inputValue()).toBe('original');expect(await inner().locator('#x').isChecked()).toBe(false)})
  it('обработчик beforeinput может отклонить ввод',async()=>{await open('<input id="x" value="original"><script>document.querySelector("#x").addEventListener("beforeinput",e=>{document.body.dataset.before=e.data;e.preventDefault()})</script>');expect((await act({kind:'type',selector:'#x',text:'changed'})).ok).toBe(false);expect(await inner().locator('body').getAttribute('data-before')).toBe('changed');expect(await inner().locator('#x').inputValue()).toBe('original')})
  it('не стирает значение при превышении maxlength и неверном числе',async()=>{await open('<input id="short" maxlength="2" value="ok"><input id="number" type="number" value="42">');expect((await act({kind:'type',selector:'#short',text:'long'})).ok).toBe(false);expect((await act({kind:'type',selector:'#number',text:'bad'})).ok).toBe(false);expect(await inner().locator('#short').inputValue()).toBe('ok');expect(await inner().locator('#number').inputValue()).toBe('42')})
  it('select не выбирает disabled option или optgroup',async()=>{await open('<select id="x"><option value="old">Old</option><option disabled value="bad">Bad</option><optgroup disabled><option value="group">Group</option></optgroup></select>');for(const value of ['bad','group','missing'])expect((await act({kind:'set',selector:'#x',value})).ok).toBe(false);expect(await inner().locator('#x').inputValue()).toBe('old')})
  it('проверяет фактическое состояние radio/checkbox после действия',async()=>{await open('<input id="r" type="radio" checked><input id="c" type="checkbox" onclick="event.preventDefault()">');expect((await act({kind:'set',selector:'#r',checked:false})).ok).toBe(false);expect((await act({kind:'set',selector:'#c',checked:true})).ok).toBe(false);expect(await inner().locator('#r').isChecked()).toBe(true);expect(await inner().locator('#c').isChecked()).toBe(false)})
})
