import fastify,{type FastifyInstance} from 'fastify'
import {afterAll,afterEach,beforeAll,beforeEach,describe,expect,it} from 'vitest'
import {chromium,type Browser,type Page} from 'playwright'
import {registerPreviewProxy} from '../apps/server/src/routes/previewProxy.js'
let app:FastifyInstance,browser:Browser,page:Page,base:string
const target='http://resources.machine.internal:5173',requests:string[]=[]
const inner=()=>page.frameLocator('iframe[title=site]')
const pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')
describe('Reader: динамические ресурсы в Chromium',()=>{
 beforeAll(async()=>{app=fastify();app.addHook('onRequest',async req=>{;(req as unknown as{user:{name:string;role:string}}).user={name:'resource-e2e',role:'user'}});app.get('/host',async(_req,reply)=>reply.type('text/html').send('<!doctype html><iframe title="site" style="width:900px;height:700px" src="/api/preview?url='+encodeURIComponent(target+'/dir/page')+'"></iframe>'));registerPreviewProxy(app,{machines:{canUse:async()=>true,bridge:{isOnline:()=>true,http:async(_agent,req)=>{requests.push(req.path);let type='text/html; charset=utf-8',body=Buffer.from('<!doctype html><meta charset="utf-8"><body><h1>Resources QA</h1><div id="root"></div></body>');if(req.path.endsWith('.png')){type='image/png';body=pixel}else if(req.path.endsWith('.js')){type='text/javascript; charset=utf-8';body=Buffer.from('window.dynamicLoaded=(window.dynamicLoaded||0)+1')}else if(req.path.endsWith('.css')){type='text/css; charset=utf-8';body=Buffer.from('#root{color:rgb(1, 2, 3)}')}return{status:200,headers:{'content-type':type},bodyBase64:body.toString('base64')}}}}});base=await app.listen({host:'127.0.0.1',port:0});browser=await chromium.launch()})
 beforeEach(async()=>{requests.length=0;page=await browser.newPage();page.setDefaultTimeout(5000);await page.goto(base+'/host');await inner().getByRole('heading').waitFor()});afterEach(async()=>{await page?.close()});afterAll(async()=>{await browser?.close();await app?.close()})
 it('Image.src загружает пиксель через машину до вставки в DOM',async()=>{const result=await inner().locator('body').evaluate(()=>new Promise(resolve=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,src:image.src});image.onerror=()=>resolve('error');image.src='/image-one.png';document.body.append(image)}));expect(result).toEqual({width:1,src:target+'/image-one.png'});expect(requests).toContain('/image-one.png')})
 it('динамический script выполняется даже при старом integrity',async()=>{await inner().locator('body').evaluate(()=>new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.integrity='sha256-invalid';script.src='/dynamic-one.js';script.integrity='sha256-still-invalid';script.onload=()=>resolve();script.onerror=()=>reject(new Error('script error'));document.head.append(script)}));expect(await inner().locator('body').evaluate(()=>(window as unknown as{dynamicLoaded:number}).dynamicLoaded)).toBe(1)})
 it('динамический stylesheet действительно применяется',async()=>{await inner().locator('body').evaluate(()=>new Promise<void>((resolve,reject)=>{const link=document.createElement('link');link.rel='stylesheet';link.href='/dynamic-one.css';link.onload=()=>resolve();link.onerror=()=>reject(new Error('css error'));document.head.append(link)}));expect(await inner().locator('#root').evaluate(el=>getComputedStyle(el).color)).toBe('rgb(1, 2, 3)')})
 it('вложенный iframe открывается с собственным контекстом Reader',async()=>{await inner().locator('body').evaluate(()=>{const frame=document.createElement('iframe');frame.title='nested';frame.src='/nested';document.body.append(frame)});await inner().frameLocator('iframe[title=nested]').getByRole('heading').waitFor();expect(requests).toContain('/nested')})
 it('poster video и source.src используют правильный upstream',async()=>{const urls=await inner().locator('body').evaluate(()=>{const video=document.createElement('video');video.poster='/poster-one.png';document.body.append(video);const source=document.createElement('source');source.src='/media.mp4';return{poster:video.poster,source:source.src,html:source.outerHTML}});expect(urls).toMatchObject({poster:target+'/poster-one.png',source:target+'/media.mp4'});expect(urls.html).toContain('/api/preview?url=');await expect.poll(()=>requests).toContain('/poster-one.png')})
 it('srcset выбирает и загружает проксированный кандидат',async()=>{const width=await inner().locator('body').evaluate(()=>new Promise<number>(resolve=>{const image=new Image();image.onload=()=>resolve(image.naturalWidth);image.onerror=()=>resolve(0);image.srcset='/small-one.png 1x, /large-one.png 2x';document.body.append(image)}));expect(width).toBe(1);expect(requests.some(path=>path==='/small-one.png'||path==='/large-one.png')).toBe(true)})
 it('setAttributeNS SVG и обычный setAttribute не обходят rewrite',async()=>{await inner().locator('body').evaluate(()=>{const img=document.createElement('img');img.setAttribute('src','/attribute-one.png');document.body.append(img);const svg=document.createElementNS('http://www.w3.org/2000/svg','image');svg.id='svg-image';svg.setAttributeNS('http://www.w3.org/1999/xlink','xlink:href','/svg-one.png');document.body.append(svg)});await expect.poll(()=>requests).toContain('/attribute-one.png');expect(await inner().locator('#svg-image').evaluate(el=>el.outerHTML)).toContain('/api/preview?url=')})
 it('innerHTML и outerHTML не запускают запросы к origin host',async()=>{const escaped:string[]=[];page.on('request',request=>{if(request.url()===base+'/html-one.png'||request.url()===base+'/outer-one.png')escaped.push(request.url())});await inner().locator('#root').evaluate(el=>{el.innerHTML='<img id="first" src="/html-one.png">'});await expect.poll(()=>requests).toContain('/html-one.png');await inner().locator('#first').evaluate(el=>{el.outerHTML='<img src="/outer-one.png">'});await expect.poll(()=>requests).toContain('/outer-one.png');expect(escaped).toEqual([])})
 it('insertAdjacentHTML и ShadowRoot.innerHTML сохраняют загрузку ресурсов',async()=>{await inner().locator('#root').evaluate(el=>{el.insertAdjacentHTML('beforeend','<img src="/adjacent-one.png">');el.attachShadow({mode:'open'}).innerHTML='<img src="/shadow-one.png">'});await expect.poll(()=>requests).toContain('/adjacent-one.png');await expect.poll(()=>requests).toContain('/shadow-one.png')})
 it('document.URL/baseURI следуют SPA без адреса прокси в пользовательском JS',async()=>{expect(await inner().locator('body').evaluate(()=>{history.pushState({},'','/next?x=1#/tab');return{url:document.URL,uri:document.documentURI,base:document.baseURI,referrer:document.referrer}})).toEqual({url:target+'/next?x=1#/tab',uri:target+'/next?x=1#/tab',base:target+'/next?x=1#/tab',referrer:''})})
})
