import{Component,createContext,useContext,useEffect,useMemo,useSyncExternalStore,useState,type ErrorInfo,type ReactNode}from'react';import type{AppCommand,AppModule,AppShellHost,ApplicationPorts,NavigationSlot}from'./contracts.js';import{createAppRuntime,type AppRuntime}from'./runtime.js'
const RuntimeContext=createContext<AppRuntime|null>(null)
export function ApplicationProvider({runtime,children}:{runtime:AppRuntime;children:ReactNode}){return <RuntimeContext.Provider value={runtime}>{children}</RuntimeContext.Provider>}
export function useAppRuntime():AppRuntime{const value=useContext(RuntimeContext);if(!value)throw new Error('ApplicationProvider is missing');return value}
function useStore<S>(store:{getState():Readonly<S>;subscribe(listener:()=>void):()=>void}){return useSyncExternalStore(store.subscribe,store.getState,store.getState)}
export function useCreateApplication(ports:ApplicationPorts,modules:readonly AppModule[]):AppRuntime{const runtime=useMemo(()=>createAppRuntime(ports,modules),[]);useEffect(()=>{void runtime.start();return()=>{void runtime.dispose()}},[runtime]);return runtime}
export function GlobalNavigation({slots}:{slots:readonly NavigationSlot[]}){return <nav aria-label="Глобальная навигация">{slots.filter(s=>s.id==='global').flatMap(s=>s.items()).map(i=><a key={i.id} href={i.href}>{i.label}</a>)}</nav>}
function NavigationSlotView({slot,testId}:{slot?:NavigationSlot;testId:string}){return <section data-testid={testId}>{slot?.items().filter(i=>i.visible?.()!==false).map(i=><a key={i.id} href={i.href}>{i.label}</a>)}</section>}
export function ChatNavigationSlot({slot}:{slot?:NavigationSlot}){return <NavigationSlotView slot={slot} testId="chat-navigation"/>}
export function ProjectsNavigationSlot({slot}:{slot?:NavigationSlot}){return <NavigationSlotView slot={slot} testId="projects-navigation"/>}
export function ShellActions(){const runtime=useAppRuntime();return <div className="app-shell__actions"><button onClick={()=>runtime.shell.actions.setCommandPaletteOpen(true)}>Команды</button><button onClick={()=>void runtime.logout()}>Выйти</button></div>}
export function CommandPalette({commands}:{commands:readonly AppCommand[]}){const runtime=useAppRuntime(),shell=useStore(runtime.shell),voice=useStore(runtime.voice);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(voice.recording)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();runtime.shell.actions.setCommandPaletteOpen(!runtime.shell.getState().commandPaletteOpen)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[runtime,voice.recording]);if(!shell.commandPaletteOpen)return null;return <div role="dialog" aria-label="Палитра команд">{commands.filter(c=>c.visible()).map(c=><button key={c.id} disabled={!c.enabled()} onClick={()=>void c.run()}>{c.label}</button>)}</div>}
export function Notices(){const runtime=useAppRuntime(),shell=useStore(runtime.shell);return <div aria-live="polite">{shell.notices.map(n=><div key={n.id} role={n.kind==='error'?'alert':'status'}>{n.message}<button aria-label="Закрыть" onClick={()=>runtime.shell.actions.dismissNotice(n.id)}>×</button></div>)}</div>}
interface BoundaryProps{moduleId:string;host:AppShellHost;children:ReactNode;onRetry():void}interface BoundaryState{error:boolean}
export class ModuleErrorBoundary extends Component<BoundaryProps,BoundaryState>{override state={error:false};static getDerivedStateFromError(){return{error:true}}override componentDidCatch(error:Error,_info:ErrorInfo){this.props.host.logError(error,{moduleId:this.props.moduleId,phase:'render'})}override render(){return this.state.error?<section role="alert">Модуль временно недоступен<button onClick={()=>{this.setState({error:false});this.props.onRetry()}}>Повторить</button></section>:this.props.children}}
export function AppShell({host}:{host:AppShellHost}){const runtime=useAppRuntime(),session=useStore(runtime.session),shell=useStore(runtime.shell);const[instance,setInstance]=useState<Awaited<ReturnType<AppRuntime['activate']>>>(null);const activate=()=>void runtime.activate().then(setInstance).catch(()=>setInstance(null));useEffect(()=>{activate();return host.location.subscribe(activate)},[runtime,host]);const slots=runtime.registry.navigation(session.currentUser),commands=runtime.registry.commands(session.currentUser);const Render=instance?.loaded.render;return <div className={`app-shell ${shell.collapsed?'is-collapsed':''}`}><aside><GlobalNavigation slots={slots}/><ChatNavigationSlot slot={slots.find(s=>s.id==='chat')}/><ProjectsNavigationSlot slot={slots.find(s=>s.id==='projects')}/><ShellActions/></aside><main>{instance&&Render?<ModuleErrorBoundary moduleId={instance.module.id} host={host} onRetry={activate}><Render route={instance.route} store={instance.store}/></ModuleErrorBoundary>:null}</main><Notices/><CommandPalette commands={commands}/></div>}
