import{createStoreCore,type Store}from'./store.js';import type{Notice,NoticePort,SessionClient,SessionUser,SettingsClient,SettingsSnapshot,VoiceClient}from'./contracts.js'
export interface SessionState{checking:boolean;currentUser:SessionUser|null;roles:readonly string[];error:string|null}
export interface SessionActions{check():Promise<SessionUser|null>;login(name:string,password:string):Promise<SessionUser|null>;logout():Promise<void>;clear():void}
export type SessionStore=Store<SessionState,SessionActions>
export function createSessionStore(client?:SessionClient):SessionStore{const core=createStoreCore<SessionState>({checking:false,currentUser:null,roles:[],error:null});const apply=(user:SessionUser|null):void=>core.setState({currentUser:user,roles:user?[...(user.roles??[]),user.role].filter((v,i,a)=>a.indexOf(v)===i):[]});return{getState:core.getState,subscribe:core.subscribe,dispose:core.dispose,actions:{async check(){core.setState({checking:true,error:null});try{const user=client?await client.check():{name:'',role:'admin'};apply(user);return user}catch(error){core.setState({error:error instanceof Error?error.message:'Session check failed'});return null}finally{core.setState({checking:false})}},async login(name,password){if(!client)return null;try{const user=await client.login({name,password});apply(user);core.setState({error:user?null:'Неверный логин или пароль'});return user}catch(error){core.setState({error:error instanceof Error?error.message:'Login failed'});return null}},async logout(){try{await client?.logout()}finally{apply(null);core.setState({error:null})}},clear(){apply(null);core.setState({error:null})}}}}
const EMPTY_SETTINGS:SettingsSnapshot={user:{},capabilities:null,llmAccess:[],sttCatalog:[],ttsCatalog:[],permissionDefaults:{},featureGates:{}}
export interface SettingsState extends SettingsSnapshot{loading:boolean;error:string|null}export interface SettingsActions{load():Promise<void>;update(patch:Readonly<Record<string,unknown>>):Promise<void>;reset():void}export type SettingsStore=Store<SettingsState,SettingsActions>
export function createSettingsStore(client:SettingsClient):SettingsStore{const core=createStoreCore<SettingsState>({...EMPTY_SETTINGS,loading:false,error:null});return{getState:core.getState,subscribe:core.subscribe,dispose:core.dispose,actions:{async load(){core.setState({loading:true,error:null});try{core.setState(await client.load())}catch(error){core.setState({error:error instanceof Error?error.message:'Settings load failed'})}finally{core.setState({loading:false})}},async update(patch){await client.save(patch);core.setState(({user})=>({user:{...user,...patch}}))},reset(){core.setState({...EMPTY_SETTINGS,error:null})}}}}
export interface VoiceState{recording:boolean;stopping:boolean;error:string|null}export interface VoiceActions{setRecording(recording:boolean):void;stop():Promise<void>;reset():void}export type VoiceStore=Store<VoiceState,VoiceActions>
export function createVoiceStore(client:VoiceClient):VoiceStore{const core=createStoreCore<VoiceState>({recording:false,stopping:false,error:null});let stopping:Promise<void>|null=null;const actions:VoiceActions={setRecording(recording){core.setState({recording})},async stop(){if(stopping)return stopping;stopping=(async()=>{core.setState({stopping:true});try{await client.stop();core.setState({recording:false,error:null})}catch(error){core.setState({error:error instanceof Error?error.message:'Audio stop failed'})}finally{core.setState({stopping:false});stopping=null}})();return stopping},reset(){core.setState({recording:false,stopping:false,error:null})}};return{getState:core.getState,subscribe:core.subscribe,actions,dispose(){void actions.stop().finally(()=>{void client.dispose?.();core.dispose()})}}}
export interface ShellState{collapsed:boolean;mobileOpen:boolean;commandPaletteOpen:boolean;notices:readonly Notice[]}export interface ShellActions{toggleCollapsed():void;setMobileOpen(open:boolean):void;setCommandPaletteOpen(open:boolean):void;dismissNotice(id:string):void;reset():void}export type ShellStore=Store<ShellState,ShellActions>&{notices:NoticePort}
export function createShellStore():ShellStore{const initial:ShellState={collapsed:false,mobileOpen:false,commandPaletteOpen:false,notices:[]};const core=createStoreCore(initial);let seq=0;const dismissNotice=(id:string):void=>core.setState(({notices})=>({notices:notices.filter(n=>n.id!==id)}));return{getState:core.getState,subscribe:core.subscribe,dispose:core.dispose,notices:{push(notice){const id=notice.id??`notice-${++seq}`;core.setState(({notices})=>({notices:[...notices,{...notice,id}]}));return id},dismiss:dismissNotice},actions:{toggleCollapsed(){core.setState(({collapsed})=>({collapsed:!collapsed}))},setMobileOpen(mobileOpen){core.setState({mobileOpen})},setCommandPaletteOpen(commandPaletteOpen){core.setState({commandPaletteOpen})},dismissNotice,reset(){core.setState(initial)}}}}
