import { afterEach, describe, expect, it, vi } from 'vitest'
import { createScenarioRunner } from './scenarioRunner'
const steps = [{ kind: 'click' as const, selector: '#first', text: '', sensitive: false }, { kind: 'type' as const, selector: '#name', text: 'Аня', sensitive: false }]
const tick = async () => { for (let i = 0; i < 5; i++) await Promise.resolve() }
function setup() { let id = 0; const send = vi.fn(), onProgress = vi.fn(); const runner = createScenarioRunner({ send, onProgress, newId: () => String(++id), settleMs: 1, timeoutMs: 100 }); runner.setReady(true); return { runner, send, onProgress } }
afterEach(() => vi.useRealTimers())
describe('последовательное воспроизведение сценария', () => {
  it('ждёт ответ первого шага перед следующим', async () => { vi.useFakeTimers(); const { runner, send } = setup(); const run = runner.run(steps, {}); await tick(); expect(send).toHaveBeenCalledTimes(1); runner.receive('local-1', { ok: true }); await vi.advanceTimersByTimeAsync(1); expect(send).toHaveBeenCalledTimes(2); runner.receive('local-2', { ok: true }); await vi.advanceTimersByTimeAsync(1); expect(await run).toEqual({ ok: true }) })
  it('не принимает чужой ответ', async () => { const { runner } = setup(); const run = runner.run(steps, {}); await tick(); expect(runner.receive('other', { ok: true })).toBe(false); runner.cancel(); await run })
  it('ожидает новую страницу после перехода', async () => { vi.useFakeTimers(); const { runner, send } = setup(); const run = runner.run(steps, {}); await tick(); runner.setReady(false); runner.receive('local-1', { ok: true }); await vi.advanceTimersByTimeAsync(10); expect(send).toHaveBeenCalledTimes(1); runner.setReady(true); await tick(); expect(send).toHaveBeenCalledTimes(2); runner.cancel(); await run })
  it('останавливается на первой ошибке', async () => { const { runner, send, onProgress } = setup(); const run = runner.run(steps, {}); await tick(); runner.receive('local-1', { ok: false, error: 'Элемент не найден' }); expect(await run).toMatchObject({ ok: false, error: expect.stringContaining('Шаг 1') }); expect(send).toHaveBeenCalledTimes(1); expect(onProgress).toHaveBeenLastCalledWith(expect.objectContaining({ status: 'failed', completed: 0 })) })
  it('отменяет ожидания и очищает таймеры', async () => { vi.useFakeTimers(); const { runner } = setup(); const run = runner.run(steps, {}); await tick(); runner.cancel(); expect(await run).toMatchObject({ ok: false }); expect(vi.getTimerCount()).toBe(0); expect(runner.receive('local-1', { ok: true })).toBe(false) })
  it('закрытие запрещает повторный запуск', async () => { const { runner } = setup(); const run = runner.run(steps, {}); runner.dispose(); expect(await run).toMatchObject({ ok: false }); expect(await runner.run(steps, {})).toMatchObject({ ok: false, error: 'Reader закрыт.' }) })
  it('проверяет секрет последнего шага до первого клика', async () => { const { runner, send } = setup(); expect(await runner.run([steps[0], { ...steps[1], sensitive: true }], {})).toMatchObject({ ok: false, error: expect.stringContaining('Шаг 2') }); expect(send).not.toHaveBeenCalled() })
  it('проверяет все селекторы до первого клика', async () => { const { runner, send } = setup(); expect(await runner.run([steps[0], { ...steps[1], selector: '' }], {})).toMatchObject({ ok: false }); expect(send).not.toHaveBeenCalled() })
  it('отвечает ошибкой при таймауте шага', async () => { vi.useFakeTimers(); const { runner } = setup(); const run = runner.run(steps, {}); await vi.advanceTimersByTimeAsync(101); expect(await run).toMatchObject({ ok: false, error: expect.stringContaining('не ответила') }); expect(vi.getTimerCount()).toBe(0) })
  it('отвечает ошибкой при таймауте страницы', async () => { vi.useFakeTimers(); const { runner, send } = setup(); runner.setReady(false); const run = runner.run(steps, {}); await vi.advanceTimersByTimeAsync(101); expect(await run).toMatchObject({ ok: false, error: expect.stringContaining('не загрузилась') }); expect(send).not.toHaveBeenCalled() })
  it('показывает прогресс и отвергает параллельный запуск', async () => { const { runner, onProgress } = setup(); const run = runner.run(steps, {}); expect(await runner.run(steps, {})).toMatchObject({ ok: false, error: expect.stringContaining('уже') }); expect(onProgress).toHaveBeenCalledTimes(1); runner.cancel(); await run; expect(onProgress).toHaveBeenLastCalledWith(expect.objectContaining({ status: 'cancelled' })) })
  it('использует снимок шагов и значений', async () => { vi.useFakeTimers(); const { runner, send } = setup(); const snapshot = steps.map(x => ({ ...x })); const run = runner.run(snapshot, {}); snapshot[1].text = 'изменено'; await tick(); runner.receive('local-1', { ok: true }); await vi.advanceTimersByTimeAsync(1); expect(send).toHaveBeenLastCalledWith('local-2', expect.objectContaining({ text: 'Аня' })); runner.cancel(); await run })
  it('ошибка транспорта не оставляет pending', async () => { vi.useFakeTimers(); const { runner, send } = setup(); send.mockImplementation(() => { throw Error('closed') }); expect(await runner.run(steps, {})).toMatchObject({ ok: false, error: expect.stringContaining('передать') }); expect(vi.getTimerCount()).toBe(0) })
})
