#!/usr/bin/env node
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
const ROOT=fileURLToPath(new URL('..',import.meta.url));const KB=join(ROOT,'docs/kb');const OUT=join(ROOT,'generated/kb')
const files=(dir)=>existsSync(dir)?readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(join(dir,e.name)):e.isFile()&&e.name.endsWith('.md')&&e.name!=='README.md'?[join(dir,e.name)]:[]):[]
const arr=(data,key)=>Array.isArray(data[key])?data[key]:data[key]?[data[key]]:[]
function parse(raw,path){const m=/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(raw);const data={};let list=null;if(m)for(const line of m[1].split(/\r?\n/)){const i=/^\s*-\s+(.+)$/.exec(line);if(i&&list){data[list].push(i[1].trim());continue}const p=/^([\w-]+):\s*(.*)$/.exec(line);if(p){list=p[2]?null:p[1];data[p[1]]=list?[]:p[2].trim()}}const body=m?raw.slice(m[0].length):raw;const id=data.id??relative(KB,path).replace(/\.md$/,'');const title=data.title??/^#\s+(.+)$/m.exec(body)?.[1]??id;let heading=title,anchor='overview',lines=[];const chunks=[];const flush=()=>{const text=lines.join('\n').trim();if(text)chunks.push({id:`${id}#${anchor}`,documentId:id,title,heading,text,tokens:tokens(`${title} ${heading} ${text} ${arr(data,'aliases').join(' ')} ${arr(data,'symbols').join(' ')} ${arr(data,'areas').join(' ')} ${arr(data,'protocols').join(' ')}`)});lines=[]};for(const line of body.split(/\r?\n/)){const h=/^(#{1,4})\s+(.+)$/.exec(line);if(h){flush();heading=h[2];anchor=heading.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'')}else lines.push(line)}flush();return{id,title,kind:data.kind??(path.includes('/features/')?'feature':'subsystem'),sourcePath:relative(ROOT,path),updated:data.updated??'',areas:arr(data,'areas'),symbols:arr(data,'symbols'),protocols:arr(data,'protocols'),tags:arr(data,'tags'),body,chunks}}
const tokens=(s)=>s.toLocaleLowerCase('ru').match(/[\p{L}\p{N}_./:-]+/gu)??[]
function build(){const documents=files(KB).sort().filter(p=>!p.includes('/log/')).map(p=>parse(readFileSync(p,'utf8'),p));const chunks=documents.flatMap(d=>d.chunks);const contentHash=createHash('sha256').update(JSON.stringify(documents)).digest('hex');return{manifest:{schemaVersion:1,project:'voiceAIChat',createdAt:new Date().toISOString(),contentHash,documents:documents.length,chunks:chunks.length},documents,chunks}}
function search(index,query,limit=10){const qt=[...new Set(tokens(query))];const N=index.chunks.length;const df=new Map(qt.map(t=>[t,index.chunks.filter(c=>c.tokens.includes(t)).length]));return index.chunks.map(c=>{let score=0;for(const t of qt){const tf=c.tokens.filter(x=>x===t).length;if(tf)score+=Math.log(1+(N-(df.get(t)??0)+.5)/((df.get(t)??0)+.5))*tf}return{...c,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
const [cmd,...args]=process.argv.slice(2)
if(cmd==='prepare'){const index=build(),stage=`${OUT}.tmp-${process.pid}`;rmSync(stage,{recursive:true,force:true});mkdirSync(stage,{recursive:true});writeFileSync(join(stage,'manifest.json'),JSON.stringify(index.manifest,null,2)+'\n');writeFileSync(join(stage,'documents.json'),JSON.stringify(index.documents,null,2)+'\n');writeFileSync(join(stage,'lexical-index.json'),JSON.stringify(index.chunks)+'\n');rmSync(OUT,{recursive:true,force:true});mkdirSync(dirname(OUT),{recursive:true});renameSync(stage,OUT);console.log(`✓ KB подготовлена: ${index.manifest.documents} документов, ${index.manifest.chunks} разделов, ${index.manifest.contentHash.slice(0,12)}`)}
else if(cmd==='verify'){const built=build();const saved=JSON.parse(readFileSync(join(OUT,'manifest.json'),'utf8'));if(saved.contentHash!==built.manifest.contentHash)throw new Error('Подготовленный KB-индекс не соответствует Markdown; выполните npm run kb:prepare');console.log(`✓ KB-индекс соответствует Markdown (${saved.contentHash.slice(0,12)})`)}
else if(cmd==='search'||cmd==='context'){const query=args.filter(a=>!a.startsWith('--')).join(' ');if(!query)throw new Error('Укажите поисковый запрос');const hits=search(build(),query,cmd==='context'?5:10);if(process.argv.includes('--json'))console.log(JSON.stringify(hits,null,2));else for(const h of hits)console.log(`\n## ${h.title} / ${h.heading}\n${h.text.replace(/\s+/g,' ').slice(0,cmd==='context'?700:280)}\nИсточник: ${h.id} · score ${h.score.toFixed(2)}`);if(!hits.length)console.log('Ничего не найдено')}
else if(cmd==='impact'){let changed=[];try{const committed=execFileSync('git',['diff','--name-only','origin/main...HEAD'],{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(Boolean);const working=execFileSync('git',['status','--porcelain'],{cwd:ROOT,encoding:'utf8'}).trimEnd().split('\n').filter(Boolean).map(line=>line.slice(3));changed=[...new Set([...committed,...working])]}catch{}const docs=build().documents;console.log('Изменённые файлы:');for(const f of changed)console.log(`  ${f}`);console.log('\nРекомендуется сверить:');const related=docs.filter(d=>d.areas.some(a=>changed.some(f=>f===a||f.startsWith(a.replace(/\/$/, '')+'/'))));for(const d of related)console.log(`  ${d.sourcePath} — изменён файл из areas`);if(!related.length)console.log('  Прямых связей areas не найдено; проверьте необходимость карточки фичи.')}
else{console.error('Доступно: prepare, verify, search <query>, context <query>, impact');process.exitCode=1}
